# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-10 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_remove_element_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_shared_procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedure',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
