# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-10 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20160810_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='fork_of',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_forks', to='api.Procedure'),
        ),
    ]
