# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-11 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_procedure_fork_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='created_by',
            new_name='originator',
        ),
    ]
