export DJANGO_SECRET_KEY='12345678'
export DJANGO_DB_NAME='sana'
export DJANGO_DB_USER='sana'
export DJANGO_DB_PASSWORD='sana'
export EMAIL_FROM='Team Delta <djrquazz@gmail.com>'
export EMAIL_HOST='smtp.example.com'
export EMAIL_HOST_USER='name@email.com'
export EMAIL_HOST_PASSWORD='stuff'
